### PR TITLE
Add Composio integration to recipes

### PR DESCRIPTION
**Pull request by cagnusmarlsen**
## Description 

This notebook shows how to integrate Composio with Weaviate. Composio provides pre-defined actions for a large number of applications like Gmail, Slack, Trello etc. and allows the creation of seamless integrations between these apps and LLMs/agents. This example uses Composio's Gmail tool and Weaviate to create an agent that can automatically respond to emails.

## Contribution Type
- [x] Integration
- [ ] Weaviate feature

## Promotion 

- X handle: https://x.com/wetbeakj
- LinkedIn account: 
- Company `@` if applicable: https://x.com/composiohq

### CODE REVIEW

**Comment by cagnusmarlsen** [comment]
I agree

**Comment by erika-cardenas** [comment]
Thanks so much for creating the recipe, @cagnusmarlsen! 🔥 I'll review it today and promote it this week.

**Comment by erika-cardenas** [comment]
Hi @cagnusmarlsen, 

This repository shares Python notebooks only, would you mind removing the `composio-weaviate-ts` folder? Much appreciated!

**Comment by cagnusmarlsen** [comment]
Hi @erika-cardenas, I've removed the js example from this pr. Thanks for reviewing!

**Comment by erika-cardenas** [comment]
Amazing, thanks for the quick turnaround @cagnusmarlsen!

**Pull request merged**
